module.exports = {
 extends: 'lighthouse:default',
 settings: {
 onlyAudits: [

 'first-contentful-paint',
 'largest-contentful-paint',
 'first-meaningful-paint',
 'speed-index',
 'interactive',
 'total-blocking-time',
 'cumulative-layout-shift',

 'color-contrast',
 'image-alt',
 'label',
 'link-name',
 'button-name',
 'document-title',
 'html-has-lang',
 'html-lang-valid',
 'meta-description',
 'aria-allowed-attr',
 'aria-hidden-body',
 'aria-hidden-focus',
 'aria-input-field-name',
 'aria-required-attr',
 'aria-roles',
 'aria-valid-attr',
 'aria-valid-attr-value',
 'bypass',
 'focus-traps',
 'focusable-controls',
 'heading-order',
 'interactive-element-affordance',
 'logical-tab-order',
 'managed-focus',
 'offscreen-content-hidden',
 'use-landmarks',
 'visual-order-follows-dom',

 'uses-responsive-images',
 'efficient-animated-content',
 'preload-lcp-image',
 'unused-css-rules',
 'unused-javascript',
 'modern-image-formats',
 'uses-optimized-images',
 'uses-text-compression',
 'uses-rel-preconnect',
 'font-display',

 'meta-viewport',
 'robots-txt',
 'hreflang',
 'canonical',
 ],
 },
 audits: [

 ],
 categories: {
 performance: {
 title: 'Performance',
 description: 'Metrics related to loading performance',
 auditRefs: [
 { id: 'first-contentful-paint', weight: 10 },
 { id: 'largest-contentful-paint', weight: 25 },
 { id: 'first-meaningful-paint', weight: 10 },
 { id: 'speed-index', weight: 10 },
 { id: 'interactive', weight: 10 },
 { id: 'total-blocking-time', weight: 30 },
 { id: 'cumulative-layout-shift', weight: 5 },
 ],
 },
 accessibility: {
 title: 'Accessibility',
 description: 'Accessibility audits',
 auditRefs: [
 { id: 'color-contrast', weight: 3 },
 { id: 'image-alt', weight: 10 },
 { id: 'label', weight: 10 },
 { id: 'link-name', weight: 3 },
 { id: 'button-name', weight: 10 },
 { id: 'document-title', weight: 3 },
 { id: 'html-has-lang', weight: 3 },
 { id: 'html-lang-valid', weight: 3 },
 { id: 'aria-allowed-attr', weight: 10 },
 { id: 'aria-hidden-body', weight: 10 },
 { id: 'aria-hidden-focus', weight: 3 },
 { id: 'aria-input-field-name', weight: 3 },
 { id: 'aria-required-attr', weight: 10 },
 { id: 'aria-roles', weight: 3 },
 { id: 'aria-valid-attr', weight: 3 },
 { id: 'aria-valid-attr-value', weight: 3 },
 { id: 'bypass', weight: 3 },
 { id: 'focus-traps', weight: 3 },
 { id: 'focusable-controls', weight: 3 },
 { id: 'heading-order', weight: 2 },
 { id: 'interactive-element-affordance', weight: 3 },
 { id: 'logical-tab-order', weight: 3 },
 { id: 'managed-focus', weight: 3 },
 { id: 'offscreen-content-hidden', weight: 3 },
 { id: 'use-landmarks', weight: 3 },
 { id: 'visual-order-follows-dom', weight: 3 },
 ],
 },
 },
};